language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  use_library: "regex"   # Uses the regex library for pattern matching
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
  - name: TEDPolicy
    max_history: 5
    epochs: 100

channels:
  slack:
    slack_token: "xoxb-8032594382982-8036368822757-rnquB80KM11iqnhFhO6UxQMQ"
    slack_signing_secret: "8caa5b6064d723eb62ea5abcf89a0822"
    slack_channel: "#recipes-parser"

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
assistant_id: 20241116-192948-international-scarfing
